[tool]
[tool.poetry]
name = "mappr"
version = "0.4.1"
description = ""
authors = ["Mateusz Klos <novopl@gmail.com>"]
repository = "https://github.com/novopl/mappr"
homepage = "https://novopl.github.io/mappr"
documentation = "https://novopl.github.io/mappr"
license = "Proprietary"
packages = [
    { include = "mappr", from = "src" },
]
include = ["LICENSE", "AUTHORS", "README.rst", "**/py.typed"]
exclude = ["tests/**", "ops/**", ".venv/**"]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"

[tool.poetry.dev-dependencies]
codecov = "^2.1.13"
coverage = "^7.3.0"
flake8 = "^6.1.0"
mypy = "^1.5.0"
peltak = "^0.30.0"
peltak-changelog = "^0.0.4"
peltak-todos = "^0.0.10"
pycodestyle = "^2.11.0"
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pytest-sugar = "^0.9.7"
pydantic = "^2.1.1"
SQLAlchemy = "^1.3.22"
Sphinx = "^7.1.2"
sphinx-autodoc-typehints = "^1.24.0"
sphinx-material = "^0.0.35"
isort = "^5.12.0"
