version: 2

jobs:
  build:
    docker:
      - image: novopl/python37
    environment:
      REVISION: << pipeline.git.revision >>
      BASE_REV: << pipeline.git.base_revision >>
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum ".circleci/config.yml" }}-{{ checksum "poetry.lock" }}

      - run:
          name: Install project dependencies
          command: |
            echo '== pwd ==================================================='
            pwd
            echo '== which pip ============================================='
            which pip
            echo '== which python =========================================='
            which python
            echo '== python --version ======================================'
            python --version
            echo '== whoami ================================================'
            whoami
            echo '== poetry install ========================================'
            echo "revision: $REVISION"
            echo "base_revision: $BASE_REVISION"
            echo '=========================================================='
            poetry config virtualenvs.in-project true
            poetry show -v
            poetry install --no-ansi
            echo '=========================================================='

      - run:
          name: Checks
          command: poetry run peltak check

      - run:
          name: Test
          command: poetry run peltak test --no-sugar --cov-xml

      - save_cache:
          key: deps-{{ checksum ".circleci/config.yml" }}-{{ checksum "poetry.lock" }}
          paths:
            - /usr/local/bin
            - /usr/local/lib/python3.6/site-packages
            - .venv
            - .mypy_cache
            - .pytest_cache

      - run:
          name: Upload coverage reports
          command: poetry run codecov

      - run:
          name: Build Documentation
          command: |
            poetry run peltak docs --recreate
            mv docs/html docs/mappr-docs
            cd docs && zip -r ../.build/mappr-docs.zip mappr-docs

      - store_test_results:
          path: .build
      - store_artifacts:
          path: .build/coverage/
          destination: coverage
      - store_artifacts:
          path: .build/mappr-docs.zip

  release:
    docker:
      - image: novopl/python37
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum ".circleci/config.yml" }}-{{ checksum "poetry.lock" }}

      - run:
          name: Install dependencies
          command: poetry install -n --no-ansi

      - run:
          name: Upload to pypi
          command: |
            poetry publish -n --build --username="$PYPI_USER" --password="$PYPI_PASS"

      - run:
          name: Create release tag
          command: |
            poetry run peltak changelog > ./__changelog.txt
            poetry run peltak release tag -m "$(poetry run peltak changelog)"
            git push origin v$(poetry run peltak version --porcelain)

      - run:
          name: Create GitHub release
          command: |
            cat ./__changelog.txt
#            export RELEASED_VERSION=$(poetry run peltak version --porcelain)
#            gh release create \
#              --repo "novopl/mappr" \
#              --title "v$RELEASED_VERSION" \
#              --notes "$(poetry run peltak changelog)" \
#              "v$RELEASE_VERSION" \
#              dist/mappr-$RELEASED_VERSION-py3-none-any.whl \
#              dist/mappr-$RELEASED_VERSION.tar.gz


  gh-pages:
    docker:
      - image: novopl/python37
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum ".circleci/config.yml" }}-{{ checksum "poetry.lock" }}

      - run:
          name: Setup
          command: |
            echo '== poetry install ========================================'
            time poetry install
            echo '== peltak --help ========================================='
            poetry run peltak --help
            echo '=========================================================='

      - run:
          name: Build docs
          command: poetry run peltak docs

      - run:
          name: Deploy gh-pages
          command: |
            git checkout gh-pages
            cp -r docs/html/* ./
            git add .
            git config user.email "${GIT_EMAIL}"
            git config user.name "${GIT_USER}"
            git commit -nm "Docs build #${CIRCLECI_BUILD_NUM}"
            git push --no-verify origin gh-pages

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: [gh-pages]
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
      - gh-pages:
          requires:
            - build
          filters:
            branches:
              only: master
