name: Common

# This workflow can only be explicitly triggered by other workflows and it contains
# common stuff we want to run on both CI and release workflows
on:
  workflow_call:


jobs:
  checks:
    name: code Checks

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project

      - name: ruff
        shell: bash
        run: uv run ruff check

      - name: isort
        shell: bash
        run: uv run isort --check-only --diff src tests

      - name: mypy
        shell: bash
        run: uv run mypy

      - name: pytest
        shell: bash
        run: |
          uv run pytest \
            --durations=3 \
            --cov-report=term:skip-covered \
            --cov=src/mappr \
            --doctest-modules \
            --doctest-report=ndiff \
            --cov-report=xml \
            --md-report \
            --md-report-flavor gfm \
            --md-report-output pytest-report.md \
            --md-report-zeros empty
          cat pytest-report.md >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
