name: Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  checks:
    name: common
    uses: ./.github/workflows/_common.yaml

  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project

      - name: Build package
        run: uv build --no-sources

      - name: Upload to pypi
        run: uv publish --token="${{ secrets.PYPI_TOKEN }}"

      - name: Create github release
        run: uv run peltak ci publish-release

  gh_release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project

      - name: Create github release
        run: uv run peltak ci publish-release

  gh_pages:
    name: Publish docs
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project

      - name: Build package
        run: uv build --no-sources

      - name: Create github release
        run: uv run peltak ci publish-release
