name: Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  checks:
    name: common
    uses: ./.github/workflows/_common.yaml

  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project

      - name: Build package
        run: uv build --no-sources

      - name: Upload to pypi
        run: uv publish --token="${{ secrets.PYPI_TOKEN }}"

  gh_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project

      - name: Create github release
        run: uv run peltak ci publish-release

  gh_pages:
    name: Publish Docs
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project

      - name: Build Docs
        run: uv run peltak mkdocs build

      - name: Deploy gh-pages
        run: |
            git fetch --all
            git branch -v
            git checkout gh-pages
            echo "=> Removing all existing files"
            find . -maxdepth 1 \
                ! -path "." \
                ! -name "docs-ng" \
                ! -name ".git" \
                ! -name ".github" \
                -exec rm -rf {} \;

            echo "=> Copying docs contents to repo root"
            cp -r docs-ng/dist/* ./
            echo "=> Removing docs source dir"
            rm -rf docs-ng

            # Switch off jekyll to handle files starting with '_' properly, see:
            #   - https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action
            #   - https://www.ianwootten.co.uk/2022/11/08/how-to-use-underscores-with-github-pages/
            touch ".nojekyll"

            echo "=> Committing and pushing changes to gh-pages"
            git add .
            git config user.email "${{secrets.GIT_EMAIL}}"
            git config user.name "${{secrets.GIT_USER}}"
            git commit -nm "Docs build #${{github.run_number}}"
            git push --no-verify origin gh-pages
            echo "=> Checking out master"
            git checkout master
